version: '2'

services:
  influxdb:
    image: influxdb
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - "${DOCKER_INFLUXDB_INIT_PORT}:8086"

  telegraf:
    image: telegraf
    volumes:
      - "${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf"
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    ports:
      - "${GRAFANA_PORT}:3000"

volumes:
  grafana-storage:
    driver: local
  influxdb-storage:
    driver: local
